import {
  Bug,
  Rat,
  BedDouble,
  Trees,
  Hexagon,
  Droplet,
  Bird,
  PawPrint,
  Axe,
  Waves,
  UtensilsCrossed,
  Store,
  Building2,
  Factory,
  GraduationCap,
  type LucideIcon,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  bug: Bug,
  rat: Rat,
  bedDouble: BedDouble,
  ant: Bug,
  trees: Trees,
  hexagon: Hexagon,
  droplet: Droplet,
  bird: Bird,
  pawPrint: PawPrint,
  axe: Axe,
  waves: Waves,
  utensilsCrossed: UtensilsCrossed,
  store: Store,
  building2: Building2,
  factory: Factory,
  graduationCap: GraduationCap,
}
